### ISSUE TITLE
Add new unknown nameids

### ISSUE THREAD

**Issue by amdigyira** [somespecialone/steam-item-name-ids#2]
### Initial Checks

- [ ] I have searched the existing requests for a duplicate and I'm sure this is something new
- [ ] I have read and followed the documentation (if possible) and still think this feature is missing

### Description

  "StatTrak\u2122 Five-SeveN | Scrawl (Factory New)": 176288629,
  "UMP-45 | Motorized (Factory New)": 176414048,
  "Nova | Dark Sigil (Minimal Wear)": 176414052,
  "XM1014 | Irezumi (Minimal Wear)": 176414050,
  "Dual Berettas | Hideout (Minimal Wear)": 176414041,
  "UMP-45 | Motorized (Minimal Wear)": 176414057,
  "StatTrak\u2122 UMP-45 | Roadblock (Field-Tested)": 176321262,
  "Sealed Graffiti | EZ": 171085471,
  "StatTrak\u2122 Glock-18 | Winterized (Well-Worn)": 176321178,
  "USP-S | Desert Tactical (Battle-Scarred)": 176369921,
  "StatTrak\u2122 Nova | Dark Sigil (Battle-Scarred)": 176414073,
  "MAC-10 | Echoing Sands (Field-Tested)": 176369906,
  "StatTrak\u2122 FAMAS | Meow 36 (Field-Tested)": 176321206,
  "StatTrak\u2122 Glock-18 | Winterized (Battle-Scarred)": 176321229,
  "SCAR-20 | Fragments (Factory New)": 176358831,
  "UMP-45 | Houndstooth (Battle-Scarred)": 176209645,
  "StatTrak\u2122 MAG-7 | Insomnia (Factory New)": 176358931,
  "Recoil Case": 176321160,
  "MAC-10 | Monkeyflage (Minimal Wear)": 176321179,
  "P90 | Neoqueen (Factory New)": 176358865

**Comment by somespecialone** [comment]
@v9lu, good day time! Can you open a PR with this ids added?

**Comment by amdigyira** [comment]
sure
